### index
GET http://localhost:8080/api/discounts
Accept: application/json
Authorization: Bearer my-secret-token

### show
GET http://localhost:8080/api/discounts/1
Authorization: Bearer my-secret-token

### create
POST http://localhost:8080/api/discounts
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "tanggal": "2026-08-01",
  "nominal": 120000
}

### update
PUT http://localhost:8080/api/discounts/1
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "nominal": 175000
}

### delete
DELETE http://localhost:8080/api/discounts/1
Authorization: Bearer my-secret-token